swagger: '2.0'

info:
  version: "0.0.0"
  title: StudyQuiz API

################################################################################
#                                   Parameters                                 #
################################################################################
parameters:
  userId:
    name: userId
    in: path
    description: The user identifier number
    type: string
    required: true
  quizId:
    name: quizId
    in: path
    description: The quiz identifier number
    type: string
    required: true
  questionId:
    name: questionId
    in: path
    description: The question identifier number
    type: string
    required: true

################################################################################
#                                           Paths                              #
################################################################################
paths:
  /:
    get:
      description: Returns the landing page.
      operationId: getHtml
      parameters: []
      responses:
        200:
          description: OK
      produces:
        - text/html
      tags:
        - "StudyQuiz"

  /quiz:
    get:
      description: Gets a array of `quiz` objects.
      operationId: getQuizArray
      parameters:
        - name: size
          in: query
          description: Size of array
          required: false
          type: integer
          format: int32
        - name: offset
          in: query
          description: Start index
          required: false
          type: integer
          format: int32
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Quiz'
        403:
          description: No permission to view this data
        default:
          description: unexpected error
      tags:
        - "StudyQuiz"
    post:
      description: Create a new quiz.
      operationId: createQuiz
      parameters:
        -
          name: quiz
          in: body
          description: Details of the new quiz
          required: true
          schema:
            $ref: '#/definitions/Quiz'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Quiz'
        403:
          description: No permission to view this data
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorModel'
      tags:
        - "StudyQuiz"

  /question:
    get:
      description: Gets a array of `question` objects.
      operationId: getQuestionArray
      parameters:
        - name: size
          in: query
          description: Size of array
          required: false
          type: integer
          format: int32
        - name: offset
          in: query
          description: Start index
          required: false
          type: integer
          format: int32
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Question'
        403:
          description: No permission to view this data
        default:
          description: unexpected error
      tags:
        - "StudyQuiz"
    post:
      description: Create a new question.
      operationId: createQuestion
      parameters:
        -
          name: question
          in: body
          description: Details of the new question
          required: true
          schema:
            $ref: '#/definitions/Question'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Question'
        403:
          description: No permission to view this data
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorModel'
      tags:
        - "StudyQuiz"

  /user:
    get:
      description: Gets a array of `user` objects.
      operationId: getUserArray
      parameters:
        - name: size
          in: query
          description: Size of array
          required: false
          type: integer
          format: int32
        - name: offset
          in: query
          description: Start index
          type: integer
          format: int32
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
        403:
          description: No permission to view this data
        default:
          description: unexpected error
      tags:
        - "StudyQuiz"
    post:
      description: Create a new user.
      operationId: createUser
      parameters:
        -
          name: user
          in: body
          description: Details of the new user
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/User'
        403:
          description: No permission to view this data
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorModel'
      tags:
        - "StudyQuiz"

  /quiz/{quizId}:
    get:
      description: Gets basic information about a quiz.
      operationId: getQuiz
      parameters:
        - $ref: '#/parameters/quizId'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Quiz'
        403:
          description: No permission to view this data
        default:
          description: unexpected error
      tags:
        - "StudyQuiz"
    post:
      description: Update a quiz.
      operationId: updateQuiz
      parameters:
        - $ref: '#/parameters/quizId'
        - name: quiz
          in: body
          description: Updated quiz details
          required: false
          schema:
            $ref: '#/definitions/Quiz'
      responses:
        200:
          description: OK
        default:
          description: unexpected error
      tags:
        - "StudyQuiz"
    delete:
      description: Delete a quiz.
      operationId: deleteQuiz
      parameters:
        - $ref: '#/parameters/quizId'
      responses:
        200:
          description: OK
        default:
          description: unexpected error
      tags:
        - "StudyQuiz"

  /quiz/{userId}/quizzes:
    get:
      description: Gets all quizzes of a user.
      operationId: getAllQuizzesOfUser
      parameters:
        - $ref: '#/parameters/userId'
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Quiz'
        403:
          description: No permission to view this data
        default:
          description: unexpected error
      tags:
        - "StudyQuiz"

  /question/{questionId}:
    get:
      description: Gets basic information about a question.
      operationId: getQuestion
      parameters:
        - $ref: '#/parameters/questionId'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Question'
        403:
          description: No permission to view this data
        default:
          description: unexpected error
      tags:
        - "StudyQuiz"
    post:
      description: Update a question.
      operationId: updateQuestion
      parameters:
        - $ref: '#/parameters/questionId'
        - name: quiz
          in: body
          description: Updated quiz details
          required: false
          schema:
            $ref: '#/definitions/Quiz'
      responses:
        200:
          description: OK
        default:
          description: unexpected error
      tags:
        - "StudyQuiz"
    delete:
      description: Delete a question.
      operationId: deleteQuestion
      parameters:
        - $ref: '#/parameters/questionId'
      responses:
        200:
          description: OK
        default:
          description: unexpected error
      tags:
        - "StudyQuiz"

  /user/{userId}:
    get:
      description: Gets basic information about an user.
      operationId: getUser
      parameters:
        - $ref: '#/parameters/userId'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/User'
        403:
          description: No permission to view this data
        default:
          description: unexpected error
      tags:
        - "StudyQuiz"
    post:
      description: Update a user.
      operationId: updateUser
      parameters:
        - $ref: '#/parameters/userId'
        - name: user
          in: body
          description: Updated user details
          required: false
          schema:
            $ref: '#/definitions/User'
      responses:
        200:
          description: OK
        default:
          description: unexpected error
      tags:
        - "StudyQuiz"
    delete:
      description: Delete a user.
      operationId: deleteUser
      parameters:
        - $ref: '#/parameters/userId'
      responses:
        200:
          description: OK
        default:
          description: unexpected error
      tags:
        - "StudyQuiz"

################################################################################
#                                     Definitions                              #
################################################################################
definitions:
  Quiz:
    type: object
    properties:
      _id:
        type: string
      questions:
        type: array
        description: Array of questionIds.
        items:
            type: string
      configuration:
        type: string
      faculty:
        type: string
      subject:
        type: string
      quizUrl:
        type: string
      challenger:
        type: string
        description: userId
      opponent:
        type: string
        description: userId
      challengerPoints:
            type: integer
            format: int32
      opponentPoints:
            type: integer
            format: int32

  Question:
    type: object
    properties:
      _id:
        type: string
      question:
        type: string
      answer:
        type: array
        items:
          type: string
      category:
        type: string
      faculty:
        type: string
      subject:
        type: string
      userId:
        type: string

  User:
    type: object
    properties:
        _id:
          type: string
        username:
          type: string
        won:
          type: integer
          format: int32
        lost:
          type: integer
          format: int32
        token:
          type: string

  ErrorModel:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      err: # wieso sollte err type: object sein bzw welche properties dann ?
        type: string
