---
swagger: "2.0"
info:
  version: "1.0.0"
  title: "Smartlocker API"

################################################################################
#                                           Paths                              #
################################################################################


paths:
  /:
    get:
      tags:
      - "Smartlocker"
      description: "Return the landing page."
      operationId: "getHtml"
      produces:
      - "text/html"
      parameters: []
      responses:
        200:
          description: "OK"
      x-swagger-router-controller: "Smartlocker"

  /combo:
    get:
      tags:
      - "Smartlocker"
      description: "Gets an array of 'combo' objects."
      operationId: "getComboArray"
      parameters:
      - $ref: "#/parameters/size"
      - $ref: "#/parameters/offset"
      responses:
        200:
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Combo"
        500:
          description: "Error on Database"
          schema:
            $ref: "#/definitions/ErrorModel"
        default:
          description: "unexpected error"
      x-swagger-router-controller: "Smartlocker"

  /timeschedule:
    get:
      tags:
      - "Smartlocker"
      description: "Gets an array of 'timeschedule' objects."
      operationId: "getTimeSchedule"
      responses:
        200:
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/TimeSchedule"
        500:
          description: "Error on Database"
          schema:
            $ref: "#/definitions/ErrorModel"
        default:
          description: "unexpected error"
      x-swagger-router-controller: "Smartlocker"


################################################################################
#                                     Definitions                              #
################################################################################

definitions:
  Combo:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
        example: 3
      name:
        type: "string"
        example: "combo 1"
      price:
        type: "number"
        format: "float"

  TimeSchedule:
    type: "object"
    properties:
      pickup_time:
        type: "string"
        format: "date-time"
        example: "10:30"
      available:
        type: "boolean"
        example: "true"

  ErrorModel:
    type: "object"
    properties:
      status:
        type: "integer"
        format: "int32"
      message:
        type: "string"
      err:
        type: "string"

################################################################################
#                                   Parameters                                 #
################################################################################

parameters:
  size:
    name: "size"
    in: "query"
    description: "Size of array to receive"
    required: false
    type: "integer"
    format: "int32"

  offset:
    name: "offset"
    in: "query"
    description: "Start index of the source"
    required: false
    type: "integer"
    format: "int32"
