---
swagger: "2.0"
info:
  version: "0.0.0"
  title: "Smartlocker API"
paths:
  /:
    get:
      tags:
      - "Smartlocker"
      description: "Return the landing page."
      operationId: "getHtml"
      produces:
      - "text/html"
      parameters: []
      responses:
        200:
          description: "OK"
      x-swagger-router-controller: "Smartlocker"
definitions: {}
