swagger: "2.0"
info:
  version: "1.0.0"
  title: "Smartlocker API"

################################################################################
#                                           Paths                              #
################################################################################


paths:
  /:
    get:
      tags:
      - "Smartlocker"
      description: "Return the landing page."
      operationId: "getHtml"
      produces:
      - "text/html"
      parameters: []
      responses:
        200:
          description: "OK"
      x-swagger-router-controller: "Smartlocker"

  /combo:
    get:
      tags:
      - "Smartlocker"
      description: "Gets an array of 'combo' objects."
      operationId: "getComboArray"
      parameters:
      - $ref: "#/parameters/size"
      - $ref: "#/parameters/offset"
      responses:
        200:
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Combo"
        500:
          description: "Error on Database"
          schema:
            $ref: "#/definitions/ErrorModel"
        default:
          description: "unexpected error"
      x-swagger-router-controller: "Smartlocker"

  /timeschedule:
    get:
      tags:
      - "Smartlocker"
      description: "Gets an array of 'timeschedule' objects."
      operationId: "getTimeSchedule"
      responses:
        200:
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/TimeSchedule"
        500:
          description: "Error on Database"
          schema:
            $ref: "#/definitions/ErrorModel"
        default:
          description: "unexpected error"
      x-swagger-router-controller: "Smartlocker"

  /order:
    get:
      tags:
      - "Smartlocker"
      description: "Gets an array of 'orders' objects"
      operationId: "getOrderArray"
      responses:
        200:
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Order"
        500:
          description: "Error on Database"
          schema:
            $ref: "#/definitions/ErrorModel"
        default:
          description: "unexpected error"
      x-swagger-router-controller: "Smartlocker"
    post:
      tags:
      - "Smartlocker"
      description: "Requests an order and gets a orderID back if successed"
      operationId: "setOrder"
      parameters:
      - $ref: "#/parameters/combo_id"
      - $ref: "#/parameters/pickup_time"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Locker_Schedule"
        404:
          description: "Not Found"
        406:
          description: "Order Not Accepted"
        default:
          description: "unexprected error"
      x-swagger-router-controller: "Smartlocker"

  /order/{orderID}:
    parameters:
    - $ref: "#/parameters/orderID"
    get:
      tags:
      - "Smartlocker"
      description: "Gets the basic informations from an order"
      operationId: "getOrder"
      parameters: []
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/UserOrder"
        404:
          description: "Not Found"
        default:
          description: "unexpected error"
      x-swagger-router-controller: "Smartlocker"

  /combo/food/{comboID}:
    parameters:
    - $ref: "#/parameters/comboID"
    get:
      tags:
      - "Smartlocker"
      description: "Gets the basic informations from a combo the food"
      operationId: "getComboFood"
      parameters: []
      responses:
        200:
          description: "OK"
          schema:
            type: "array"
            items:
             $ref: "#/definitions/Food"
        404:
          description: "Not Found"
        default:
          description: "unexpected error"
      x-swagger-router-controller: "Smartlocker"

  /combo/ingredient/{comboID}:
     parameters:
     - $ref: "#/parameters/comboID"
     get:
      tags:
      - "Smartlocker"
      description: "Gets the basic informations from the food ingredients"
      operationId: "getComboIngredient"
      parameters: []
      responses:
        200:
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Ingredient"
        404:
          description: "Not Found"
        default:
          description: "unexpected error"
      x-swagger-router-controller: "Smartlocker"

  /close/combo/:
      put:
        tags:
        - "Smartlocker"
        description: "Sets a Combo to unavailable"
        operationId: "updateCombo"
        parameters:
        - $ref: "#/parameters/combo_id"
        - $ref: "#/parameters/combo_name"
        - $ref: "#/parameters/combo_price"
        responses:
          200:
            description: "OK"
            schema:
              items:
                $ref: "#/definitions/Combo"
          404:
            description: "Not Found"
          default:
            description: "unexpected error"
      x-swagger-router-controller: "Smartlocker"

  /close/order/:
      put:
        tags:
        - "Smartlocker"
        description: "Sets an order to served"
        operationId: "updatedOrder"
        parameters:
        - $ref: "#/parameters/combo_id"
        - $ref: "#/parameters/pickup_time"
        - $ref: "#/parameters/locker_nr"
        responses:
          200:
            description: "OK"
          404:
            description: "Not Found"
          default:
            description: "unexpected error"
      x-swagger-router-controller: "Smartlocker"

  /locker:
      get:
        tags:
        - "Smartlocker"
        description: "Gets an array of 'orders' objects"
        operationId: "getLockerArray"
        responses:
          200:
            description: "OK"
            schema:
              type: "array"
              items:
                $ref: "#/definitions/Locker"
          500:
            description: "Error on Database"
            schema:
             $ref: "#/definitions/ErrorModel"
          default:
            description: "unexpected error"
      x-swagger-router-controller: "Smartlocker"

################################################################################
#                                     Definitions                              #
################################################################################

definitions:

  Locker:
    type: "object"
    properties:
      nr:
        type: "integer"
        format: "int32"
        example: 1002
      PIN:
        type: "integer"
        format: "int32"
        example: 6832

  UserOrder:
    type: "object"
    properties:
      id:
        type: "string"
        example: "df7cca36-3d7a-40f4-8f06-ae03cc22f041"
      combo_id:
        type: "integer"
        format: "int32"
        example: 21
      ordered_at:
        type: "string"
        format: "date-time"
        example: "1985-04-12T23:20:50Z"
      pickup_time:
        type: "string"
        format: "date-time"
        example: "10:30"
      served:
        type: "boolean"
        example: "true = 1, false = 0"
      locker_nr:
        type: "integer"
        format: "int32"
        example: 1002
      PIN:
        type: "integer"
        format: "int32"
        example: 6832

  Order:
    type: "object"
    properties:
      comboID:
        type: "integer"
        format: "int32"
        example: 1
      combo_name:
        type: "string"
        example: "combo 1"
      locker_nr:
        type: "integer"
        format: "int32"
        example: 1002
      pickup_time:
        type: "string"
        format: "date-time"
        example: "10:30"
      served:
        type: "boolean"
        example: "true = 1, false = 0"

  Locker_Schedule:
    type: "object"
    properties:
      pickup_time:
        type: "string"
        format: "date-time"
        example: "10:30"
      locker_nr:
        type: "integer"
        format: "int32"
        example: 1002
      orders_id:
        type: "string"
        example: "df7cca36-3d7a-40f4-8f06-ae03cc22f041"

  Ingredient:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
        example: 22
      name:
        type: "string"
        example: "Raw Rice"

  Food:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
        example: 34
      name:
        type: "string"
        example: "Cooked Rice"

  Combo:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
        example: 3
      name:
        type: "string"
        example: "combo 1"
      price:
        type: "number"
        format: "float"
      combo_available:
        type: "boolean"
        example: "true = 1, false = 0"

  TimeSchedule:
    type: "object"
    properties:
      pickup_time:
        type: "string"
        format: "date-time"
        example: "10:30"
      schedule_available:
        type: "boolean"
        example: "true = 1, false = 0"

  ErrorModel:
    type: "object"
    properties:
      status:
        type: "integer"
        format: "int32"
      message:
        type: "string"
      err:
        type: "string"

################################################################################
#                                   Parameters                                 #
################################################################################

parameters:

  combo_id:
    name: "combo_id"
    in: "query"
    description: "The combo identifier number"
    required: true
    type: "integer"
    format: "int32"

  combo_name:
    name: "combo_name"
    in: "query"
    description: "The combo name"
    required: true
    type: "string"

  combo_price:
    name: "combo_price"
    in: "query"
    description: "The combo price"
    required: true
    type: "number"
    format: "float"

  comboID:
    name: "comboID"
    in: "path"
    description: "The combo identifier number"
    required: true
    type: "integer"
    format: "int32"

  locker_nr:
    name: "locker_nr"
    in: "query"
    description: "The locker identifier number"
    required: true
    type: "integer"
    format: "int32"

  pickup_time:
    name: "pickup_time"
    in: "query"
    description: "The time from schedule"
    required: true
    type: "string"

  order_id:
    name: "order_id"
    in: "query"
    description: "The order identifier string"
    required: true
    type: "string"

  orderID:
    name: "orderID"
    in: "path"
    description: "The order identifier string"
    required: true
    type: "string"

  size:
    name: "size"
    in: "query"
    description: "Size of array to receive"
    required: false
    type: "integer"
    format: "int32"

  offset:
    name: "offset"
    in: "query"
    description: "Start index of the source"
    required: false
    type: "integer"
    format: "int32"
